# Generated by Django 4.1.7 on 2023-03-29 15:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Nids',
            fields=[
                ('flow_id', models.IntegerField(primary_key=True, serialize=False)),
                ('protocol', models.CharField(max_length=10)),
                ('timestamp', models.DateTimeField()),
                ('flow_duration', models.FloatField()),
                ('total_fwd_packets', models.IntegerField()),
                ('total_bwd_packets', models.IntegerField()),
                ('total_fwd_packet_size', models.IntegerField()),
                ('total_bwd_packet_size', models.IntegerField()),
                ('total_fwd_payload_size', models.IntegerField()),
                ('total_bwd_payload_size', models.IntegerField()),
            ],
        ),
    ]
