# Generated by Django 4.1.7 on 2023-03-30 07:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TypingStats',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField()),
                ('keystroke_counter', models.IntegerField()),
                ('erase_keys_counter', models.IntegerField()),
                ('erase_keys_percentage', models.FloatField()),
                ('press_press_average_interval', models.FloatField()),
                ('press_press_stddev_interval', models.FloatField()),
                ('press_release_average_interval', models.FloatField()),
                ('press_release_stddev_interval', models.FloatField()),
                ('word_counter', models.IntegerField()),
                ('word_average_length', models.FloatField()),
                ('word_stddev_length', models.FloatField()),
                ('active_apps_average', models.FloatField()),
                ('current_app', models.CharField(max_length=255)),
                ('penultimate_app', models.CharField(max_length=255)),
                ('current_app_foreground_time', models.IntegerField()),
                ('current_app_average_processes', models.FloatField()),
                ('current_app_stddev_processes', models.FloatField()),
                ('cpu_percent', models.IntegerField(default=0)),
                ('ram_percent', models.IntegerField(default=0)),
                ('bytes_sent', models.IntegerField(default=0)),
                ('bytes_received', models.IntegerField(default=0)),
            ],
            options={
                'db_table': 'typing_stats',
            },
        ),
        migrations.AlterModelTable(
            name='nids',
            table='nids',
        ),
    ]
